name: Little Rock Plumbing
favicon: null
layout_spectrum: 0.04785
typography_spectrum: 0.16368797002360225
title: Associated Plumbers 501-666-9483
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfef8'
    - '#166fc9'
    - '#6abcee'
    - '#3195e1'
    - '#042337'
  brandStrength: 0.5
  lightness: 0.9860056792385876
  saturation: 0.30788220139220357
  rhythmicContrast: 0.10379409091547132
purpose: []
