name: Little Rock Plumbing
favicon: null
layout_spectrum: 0.99707
typography_spectrum: 0.95605
title: Associated Plumbers 501-666-9483
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfef8'
    - '#166fc9'
    - '#6abcee'
    - '#3195e1'
    - '#042337'
  brandStrength: 0.9375
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 1
purpose: []
